name: CD

on: [push]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/*.jar
    - name: Deploy Coverage reports documentation
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: cov
        publish_dir: target/site/jacoco