name: Publish coverage reports
on:
  workflow_run:
    workflows: ["CI"] 
    branches: 
      - master
    types: 
      - completed
jobs:
  deploy-coverage:
    name: Deploy Coverage Reports
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
      - run: mvn package
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
      - name: Deploy Coverage reports documentation
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: cov
          publish_dir: target/site/jacoco
