name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - run: mvn --batch-mode test